name: Gradle Build CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: './gradlew build'

      - uses: actions/upload-artifact@v3
        with:
          name: Island Menu Jar
          path: build/libs/*.jar