name: Gradle Build CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: './gradlew build'

      - uses: actions/upload-artifact@v4
        with:
          name: Island Menu Jar
          path: build/libs/*.jar