name: Gradle Build CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 17
          cache: 'gradle'

      - name: Build
        run: './gradlew build --no-daemon'

      - uses: actions/upload-artifact@v3
        with:
          name: Island Menu Jar
          path: build/libs/*.jar